# Generated by Django 5.1.7 on 2025-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_alter_servicerendered_service_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerendered',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerendered',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerendered',
            name='service_type',
            field=models.CharField(choices=[('spa', 'Spa'), ('home', 'Home')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spasessionbooking',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Swedish massage - 50 minutes - ₦25,000.00', 'Swedish massage - 50 minutes - ₦25,000.00'), ('Deep tissue massage - 1 hour - ₦30,000.00', 'Deep tissue massage - 1 hour - ₦30,000.00'), ('Hot stone massage - 1 hour - ₦35,000.00', 'Hot stone massage - 1 hour - ₦35,000.00'), ('Aroma therapy massage - 1 hour - ₦40,000.00', 'Aroma therapy massage - 1 hour - ₦40,000.00'), ('Couple massage with host stone - 1 hour - ₦70,000.00', 'Couple massage with host stone - 1 hour - ₦70,000.00'), ('Feet/reflexology - 20 minutes - ₦15,000.00', 'Feet/reflexology - 20 minutes - ₦15,000.00'), ('Back massage - 20 minutes - ₦15,000.00', 'Back massage - 20 minutes - ₦15,000.00'), ('Kid massage - 20 minutes - ₦10,000.00', 'Kid massage - 20 minutes - ₦10,000.00'), ('Classic facial - 60 minutes - ₦20,000.00', 'Classic facial - 60 minutes - ₦20,000.00'), ('Glowing facial - 60 minutes - ₦25,000.00', 'Glowing facial - 60 minutes - ₦25,000.00'), ('RF facial - 75 minutes - ₦30,000.00', 'RF facial - 75 minutes - ₦30,000.00'), ('Anti-aging facial - 90 minutes - ₦30,000.00', 'Anti-aging facial - 90 minutes - ₦30,000.00'), ('Acne treatment facial - 60 minutes - ₦30,000.00', 'Acne treatment facial - 60 minutes - ₦30,000.00'), ('Sugar body scrub - 60 minutes - ₦40,000.00', 'Sugar body scrub - 60 minutes - ₦40,000.00'), ('Moroccan body scrub - 60 minutes - ₦50,000.00', 'Moroccan body scrub - 60 minutes - ₦50,000.00'), ('Teeth whitening - 60 minutes - ₦30,000.00', 'Teeth whitening - 60 minutes - ₦30,000.00'), ('Full body wax - ₦60,000.00', 'Full body wax - ₦60,000.00'), ('Full leg wax - ₦20,000.00', 'Full leg wax - ₦20,000.00'), ('Half leg wax - ₦10,000.00', 'Half leg wax - ₦10,000.00'), ('Full hand wax - ₦20,000.00', 'Full hand wax - ₦20,000.00'), ('Half hand wax - ₦10,000.00', 'Half hand wax - ₦10,000.00'), ('Under arm wax - ₦10,000.00', 'Under arm wax - ₦10,000.00'), ('Brazilian wax (Bikini) - ₦20,000.00', 'Brazilian wax (Bikini) - ₦20,000.00'), ('Chin wax - ₦3,000.00', 'Chin wax - ₦3,000.00'), ('Upper lip wax - ₦3,000.00', 'Upper lip wax - ₦3,000.00'), ('Eye brow waxing - ₦8,000.00', 'Eye brow waxing - ₦8,000.00'), ('Vagina steam - ₦15,000.00', 'Vagina steam - ₦15,000.00'), ('Sauna - ₦10,000.00', 'Sauna - ₦10,000.00'), ('Pedicure & manicure - ₦15,000.00', 'Pedicure & manicure - ₦15,000.00'), ('Steam - ₦10,000.00', 'Steam - ₦10,000.00')], max_length=200, null=True),
        ),
    ]
